variables:
  CONTAINER_APPLICATION_IMAGE: registry.gitlab.ceh.ac.uk/eip/hello-world:app-$CI_BUILD_REF_NAME

build_image:
  stage: deploy
  image: gitlab/dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.ceh.ac.uk
    - docker build -t $CONTAINER_APPLICATION_IMAGE .
    - docker push $CONTAINER_APPLICATION_IMAGE
  only:
    - master